window.EDITCAPS_CONFIG = {
  supabaseUrl: 'https://floccoqkcgkgtmasjukb.supabase.co',
  supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsb2Njb3FrY2drZ3RtYXNqdWtiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTY2MjExMiwiZXhwIjoyMDg3MjM4MTEyfQ.4J18vXkdh04wmhqsRzfZYp79xwC6sxGxhgwGMSug9z8',
  paypalClientId: 'ATMeQVKdjHls1DV6xgcQFFyfy5D6XIY8_FEeTCY9nUPuESstJMgufD-OWsDRSLdyBHw90eav_3rOyR7Z'
};
